### ISSUE TITLE
use perl-install instead of perl-build?

### ISSUE THREAD

**Issue by xtetsuji** [ytnobody/plenvsetup#4]
[perl-install](https://github.com/skaji/perl-install) is released at Dec 2019. It does not use (system) perl to create user perl environment. It is substitute of [perl-build](https://github.com/tokuhirom/Perl-Build).

Currently plenvsetup setups perl-build. However some modern OS which do not have general system perl increase. :cry:

Some options are available:

- (not changing) plenvsetup uses perl-build.
- (changing) plenvsetup uses perl-install.
- (offer choice) users can choice that plenvsetup installs either perl-build or perl-install.

**Comment by ytnobody** [comment]
Many thanks for your advice!

Basically, plenvsetup still use perl-build. However, another plenvsetup variant that uses perl-install have to be made.

This means, plenvsetup and their variant never contains any options that changes their behavior. Offering any options, plenvsetup be complex.

BTW, Do you have any idea of name for new variant?

**Comment by ytnobody** [comment]
@xtetsuji I created a pull-request instead of create a variant, because too easy to use perl-install through plenvsetup.

Please check it. 
Best regards.

**Comment by ytnobody** [comment]
Now merged perl-install feature :)
